import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Button, Typography, Avatar } from '@material-ui/core';
import { deepOrange } from '@material-ui/core/colors';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Avatar style={{ backgroundColor: deepOrange[500] }}>N</Avatar>
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
        <Button variant="contained" color="primary">
          Teste
        </Button>
        <h1>Headerr h1</h1>
        <Typography element="h1" variant="subtitle2">
          Header h1 tipografia
        </Typography>
      </main>

      <footer className={styles.footer}>Todos os direitos reservados</footer>
    </div>
  );
}
